### PR TITLE
0.12.1 (with geventhttpclient)

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

As an alternative to #3. It looks like `geventhttpclient` is actually an optional dependency, as everything appears to function normally otherwise, and `fasthttp` is in `contrib`, but it does claim it as an [actual dependency](https://github.com/locustio/locust/blob/0.12.1/setup.py#L51). Anyhow, this attempts removing the offending test file. It could be good to get this clarified upstream, but am also looking into packaging `geventhttpclient`, which should be a relatively straightforward `staged-recipes` PR, but you never know.

Also, as promised, added myself to help maintain! :balloon:

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
Hooray :green_heart: . Your call whether to wait until https://github.com/conda-forge/staged-recipes/pull/9913 lands, or go with this as-is and do a `0.12.1_1` whenever that makes it through the process.

**Comment by bollwyvl** [comment]
https://github.com/conda-forge/staged-recipes/pull/9913 landed, so I've gone ahead and added `geventhttpclient` and removed the nasty test hack.

**Comment by bollwyvl** [comment]
:tada:

**Comment by carlodri** [comment]
Sorry for the wait @bollwyvl! I'm totally stuck in a migration between two jobs and things are quite messy at the moment! I'll do my best to get things going ASAP...

**Comment by bollwyvl** [comment]
No worries at all! Thanks for the review!

**Pull request merged**
